app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

app/website/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
        path('', views.home, name='home'),
        path('player', views.player, name='player'),
        path('add_player', views.add_player, name='add_player'),
        path('match', views.match, name='match'),
        path('add_match', views.add_match, name='add_match'),
        path('rating', views.rating, name='rating'),
        path('controlcenter', views.control_center, name='control_center'),
        path('login_page', views.login_page, name='login_page'),
        path('logout', views.logout_user, name='logout_user'),
]

app/website/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    #total_games
    #won_games
    #curr_rating
    #prev_rating

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Match(models.Model):
    player_one = models.ForeignKey(Player, on_delete=models.PROTECT, related_name='as_player_one')
    score_one = models.IntegerField(null=False)
    player_two = models.ForeignKey(Player, on_delete=models.PROTECT, related_name='as_player_two')
    score_two = models.IntegerField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    # order or id?

    def __str__(self):
        return f"Match: {self.player_one} vs. {self.player_two} ({self.score_one}:{self.score_two})"

class RatingRecords(models.Model):
    player = models.ForeignKey(Player, on_delete=models.PROTECT)
    rating = models.FloatField(null=False)
    match = models.ForeignKey(Match, on_delete=models.DO_NOTHING, null=True)
    #created_at

class EloParameter(models.Model):
    k_index = models.IntegerField(null=False)
    start_elo = models.IntegerField(null=False)

app/website/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Player, Match, EloParameter

class LoginForm(forms.ModelForm):
    first_name = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя'}))
    password = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя'}))

    class Meta:
        model = User
        fields = '__all__'

class AddPlayerForm(forms.ModelForm):
    first_name = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'class': 'add-player-input', 'placeholder': 'Имя'}))
    last_name = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'class': 'add-player-input', 'placeholder': 'Фамилия'}))

    class Meta:
        model = Player
        fields = '__all__'

class AddMatchForm(forms.ModelForm):
    player_one = forms.ModelChoiceField(queryset=Player.objects.all(), empty_label='Игрок 1', widget=forms.Select(attrs={'class': 'match-player'}))
    score_one = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class': 'match-score', 'min': '0', 'value': '0'}))
    player_two = forms.ModelChoiceField(queryset=Player.objects.all(), empty_label='Игрок 2', widget=forms.Select(attrs={'class': 'match-player'}))
    score_two = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class': 'match-score', 'min': '0', 'value': '0'}))

    class Meta:
        model = Match
        fields = '__all__'

class EloParameterForm(forms.ModelForm):
    k_index = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    start_elo = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = EloParameter
        fields = '__all__'

app/website/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from .models import Player, Match, RatingRecords, EloParameter
from django.db.models import Window, F
from django.db.models.functions import Rank
from .forms import AddPlayerForm, AddMatchForm, EloParameterForm
from django.contrib import messages
from .elo_calc import update_rating
from .queries import get_curr_rating
from django.core.paginator import Paginator

def login_page(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You have been logged in!')
            return redirect('home')
        else:
            messages.success(request, 'There was error with logging in. Please, try again...')
            return redirect('login_page')
    else:
        return render(request, 'login_page.html', {})

def logout_user(request):
    logout(request)
    messages.success(request, 'You have logged out')
    return redirect('home')

def control_center(request):
    if request.user.is_authenticated:
        parameters = EloParameter.objects.first()
        if request.method == 'POST':
            elo_parameter_form = EloParameterForm(request.POST, instance=parameters)
            if elo_parameter_form.is_valid():
                elo_parameter_form.save()
                # recalculate all ratings
            return redirect('control_center')
        else:
            elo_parameter_form = EloParameterForm(instance=parameters)
            return render(request, 'control_center.html', {'elo_parameter_form': elo_parameter_form})
    else:
        messages.success(request, 'You must be logged in to see that page')
        return redirect('home')


def home(request):
    curr_rating = get_curr_rating()
    players = curr_rating.annotate(
        rank=Window(
            expression=Rank(),
            order_by=F('curr_rating').desc()
        )
    ).order_by('rank')
    players_paginator = Paginator(players, 20)
    players_page_number = request.GET.get('players_page', 1)
    players_page_obj = players_paginator.get_page(players_page_number)

    matches = Match.objects.all().order_by('-created_at')
    matches_paginator = Paginator(matches, 20)
    matches_page_number = request.GET.get('matches_page', 1)
    matches_page_obj = matches_paginator.get_page(matches_page_number)

    if request.user.is_authenticated:
        add_player_form = AddPlayerForm()
        add_match_form = AddMatchForm()
        return render(
            request,
            'home.html',
            {'players_page_obj': players_page_obj, 'matches_page_obj': matches_page_obj, 'add_player_form': add_player_form, 'add_match_form': add_match_form})
    else:
        return render(request, 'home.html', {'players_page_obj': players_page_obj, 'matches_page_obj': matches_page_obj})

def player(request):
    players = Player.objects.all()

    return render(request, 'player.html', {'players': players,})

def add_player(request):
    if request.method == "POST":
        add_player_form = AddPlayerForm(request.POST)
        if add_player_form.is_valid():

            # add player into the db
            player = add_player_form.save()

            # add starting rating into the db
            parameters = EloParameter.objects.first()
            rating_record = RatingRecords(player=player, rating=parameters.start_elo)
            rating_record.save()

            messages.success(request, 'Новый игрок добавлен')
        return redirect('home')
    else:
        add_player_form = AddPlayerForm()
        return render(request, 'add_player.html', {'form': add_player_form})


def match(request):
    matches = Match.objects.all().order_by('-created_at')
    return render(request, 'match.html', {'matches': matches})

def add_match(request):
    if request.method == 'POST':
        add_match_form = AddMatchForm(request.POST)
        if add_match_form.is_valid():
            match = add_match_form.save()

            # get curr rating
            curr_rating = get_curr_rating()
            player_one = curr_rating.get(pk=match.player_one.id)
            player_two = curr_rating.get(pk=match.player_two.id)

            # calc new rating
            upd_rating_one, upd_rating_two = update_rating(player_one.curr_rating, match.score_one, player_two.curr_rating, match.score_two)
            
            # update rating
            RatingRecords(player=match.player_one, rating=upd_rating_one, match=match).save()
            RatingRecords(player=match.player_two, rating=upd_rating_two, match=match).save()
            messages.success(request, 'Новый матч добавлен')
        return redirect('home')
    else:
        add_match_form = AddMatchForm()
        return render(request, 'add_match.html', {'form': add_match_form})

def rating(request):
    records = RatingRecords.objects.all()
    return render(request, 'rating.html', {'records': records})

app/website/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Рейтинг Эло</title>
    <link rel="icon" href="{% static 'favicon.png' %}"/>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    {% include 'navbar.html' %}

    <div class="overlay"></div>

    <div class="sidebar">
        <ul>
            <li><a href="{% url 'home' %}#player-section">Рейтинг</a></li>
            <li><a href="{% url 'home' %}#match-section">История матчей</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'control_center' %}">Настройки</a></li>
            {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <a href="{% url 'logout_user' %}" class="cta-button">Выйти</a>
        {% else %}
        <a href="{% url 'login_page' %}" class="cta-button">Войти</a>
        {% endif %}
    </div>

    {% block content %}
    {% endblock %}

    <script>
        // Wait until the DOM is fully loaded
        document.addEventListener('DOMContentLoaded', () => {
            // Sidebar control
            const burger = document.querySelector('.burger');
            const sidebar = document.querySelector('.sidebar')
            const overlay = document.querySelector('.overlay')

            burger.addEventListener('click', () => {
                burger.classList.toggle('open');
                overlay.classList.toggle('active');
                sidebar.classList.toggle('active');
                if (document.body.style.overflow === 'hidden') {
                    document.body.style.overflow = '';
                } else {
                    document.body.style.overflow = 'hidden';
                }
            });
            document.addEventListener('click', (e) => {
                if (burger.classList.contains('open') && !sidebar.contains(e.target) && !burger.contains(e.target)) {
                    burger.classList.remove('open');
                    sidebar.classList.remove('active');
                    overlay.classList.remove('active');
                    document.body.style.overflow = '';
                }
            });
                // Close when clicking a link or button inside menu
            sidebar.addEventListener('click', (e) => {
                if (e.target.closest('a, button')) {
                    burger.classList.remove('open');
                    sidebar.classList.remove('active');
                    overlay.classList.remove('active');
                    document.body.style.overflow = '';
                }
            });
        });
    </script>
</body>
</html>

app/website/templates/control_center.html
{% extends 'base.html' %}

{% block content %}
<section>
    <div class="text-container">
        <h2>Базовые параметры</h2>
    </div>
    <div class="control-panel">
        <div class="cp-left">
            {% if elo_parameter_form %}
            <form method="POST" action="{% url 'control_center' %}">
                {% csrf_token %}
                <div class="base-settings">
                    <label for="id_start_elo">Стартовый Рейтинг:</label>
                    {{ elo_parameter_form.start_elo }}
                </div>
                <div class="base-settings">
                    <label for="id_k_index">K-индекс:</label>
                    {{ elo_parameter_form.k_index }}
                </div>
                <button type="submit" class="cta-button">Изменить</button>
                <p><em>Изменение приведет к перерасчету рейтинга всех игроков!</em></p>
            </form>
            {% else %}
            <p>Параметры не настроены</p>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

app/website/templates/home.html
{% extends 'base.html' %}

{% block content %}
<section id="player-section">
    <div class="text-container">
        <h2>Рейтинг Игроков</h2>
    </div>

    {% if players_page_obj %}
    <table class="table-players">
        <colgroup>
            <col class="col-rank">
            <col class="col-player">
            <col class="col-rating">
        </colgroup>
        <thead>
            <tr>
                <th class="t-rank">Ранг</th>
                <th class="t-player">Имя</th>
                <th class="t-rating">Рейтинг</th>
            </tr>
        </thead>
        <tbody>
            {% for player in players_page_obj %}
            <tr>
                <td class="t-rank">{{ player.rank }}</td>
                <td class="t-player">{{ player.first_name }} {{ player.last_name }}</td>
                <td class="t-rating">{{ player.curr_rating|floatformat:0 }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
            <span class="prev">
                {% if players_page_obj.has_previous %}
                    <a href="?players_page=1#player-section">◁</a>
                    <a href="?players_page={{ players_page_obj.previous_page_number }}#player-section">◀</a>
                {% endif %}
            </span>
            <span class="current">
                Стр. {{ players_page_obj.number }} из {{ players_page_obj.paginator.num_pages }}
            </span>
            <span class="next">
                {% if players_page_obj.has_next %}
                    <a href="?players_page={{ players_page_obj.next_page_number }}#player-section">▶</a>
                    <a href="?players_page={{ players_page_obj.paginator.num_pages }}#player-section">▷</a>
            {% endif %}
            </span>
        <span>
    </div>
    {% else %}
    <p>Данные отсутсвуют.</p>
    {% endif %}
</section>

{% if user.is_authenticated %}
<section>
    <div class="text-container">
        <h2>Панель Управления</h2>
    </div>
    <div class="control-panel">
        <div class="cp-left">
            <form method="POST" action="{% url 'add_player' %}">
                <h3>Новый Игрок</h3>
                {% csrf_token %}
                {{ add_player_form.first_name }}
                {{ add_player_form.last_name }}
                <button type="submit" class="cta-button">Добавить</button>
            </form>
        </div>
        <div class="cp-right">
            <form method="POST" action="{% url 'add_match' %}">
                <h3>Новый Матч</h3>
                {% csrf_token %}
                <div>
                {{ add_match_form.player_one }}
                {{ add_match_form.score_one }}
                </div>
                <div>
                {{ add_match_form.player_two }}
                {{ add_match_form.score_two }}
                </div>
                  <button type="submit" class="cta-button">Добавить</button>
            </form>
        </div>
    </div>
</section>
{% endif %}



<section id="match-section">
    <div class="text-container">
        <h2>История Матчей</h2>
    </div>

    {% if matches_page_obj %}
    <table class="table-matches">
        <colgroup>
            <col class="col-date">
            <col class="col-player1">
            <col class="col-result">
            <col class="col-player2">
        </colgroup>
        <thead>
            <tr>
                <th class="t-date">Дата</th>
                <th class="t-player1"></th>
                <th class="t-result">Результат</th>
                <th class="t-player2"></th>
            </tr>
        </thead>
        <tbody>
            {% for match in matches_page_obj %}
            <tr>
                <td class="t-date">{{ match.created_at|date:"d.m.Y"}}</td>
                <td class="t-player1">{{ match.player_one.first_name}}</td>
                <td class="t-result">{{ match.score_one }}:{{ match.score_two }}</td>
                <td class="t-player2">{{ match.player_two.first_name}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
            <span class="prev">
                {% if matches_page_obj.has_previous %}
                    <a href="?matches_page=1#match-section">◁</a>
                    <a href="?matches_page={{ matches_page_obj.previous_page_number }}#match-section">◀</a>
                {% endif %}
            </span>
            <span class="current">
                Стр. {{ matches_page_obj.number }} из {{ matches_page_obj.paginator.num_pages }}
            </span>
            <span class="next">
                {% if matches_page_obj.has_next %}
                    <a href="?matches_page={{ matches_page_obj.next_page_number }}#match-section">▶</a>
                    <a href="?matches_page={{ matches_page_obj.paginator.num_pages }}#match-section">▷</a>
            {% endif %}
            </span>
        <span>
    </div>
    {% else %}
    <p>Данные отсутсвуют.</p>
    {% endif %}
</section>
{% endblock %}

app/website/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
       <div class="left">
            <img src="images/logo.svg">
            <h2>РЕЙТИНГ ЭЛО</h2>
       </div> 
       <div class="right">
            <ul>
                <li><a href="index.html">Рейтинг</a></li>
                <li><a href="index.html">История матчей</a></li>
            </ul>
            <a href="index.html" class="cta-button">Войти</a>
       </div>
        <a class="burger" href="#">
            <span></span>
            <span></span>
            <span></span>
        </a>
    </header>

    <section>
        <div class="text-container">
            <h2>Рейтинг Игроков</h2>
        </div>
        <table class="table-players">
            <colgroup>
                <col class="col-rank">
                <col class="col-player">
                <col class="col-rating">
            </colgroup>
            <thead>
                <tr>
                    <th class="t-rank">Ранг</th>
                    <th class="t-player">Имя</th>
                    <th class="t-rating">Рейтинг</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="t-rank">1</td>
                    <td class="t-player">Алмасбек Утегенов</td>
                    <td class="t-rating">1500</td>
                </tr>
                <tr>
                    <td class="t-rank">1</td>
                    <td class="t-player">Алмасбек Утегенов</td>
                    <td class="t-rating">1500</td>
                </tr>
                <tr>
                    <td class="t-rank">1</td>
                    <td class="t-player">Алмасбек Утегенов</td>
                    <td class="t-rating">1500</td>
                </tr>
            </tbody>
        </table>
    </section>


    <section>
        <div class="text-container">
            <h2>История Матчей</h2>
        </div>
        <table class="table-matches">
            <colgroup>
                <col class="col-date">
                <col class="col-player1">
                <col class="col-result">
                <col class="col-player2">
            </colgroup>
            <thead>
                <tr>
                    <th class="t-date">Дата</th>
                    <th class="t-player1"></th>
                    <th class="t-result">Результат</th>
                    <th class="t-player2"></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="t-date">08.12.25</td>
                    <td class="t-player1">Алмасбек Утегенов</td>
                    <td class="t-result">3:2</td>
                    <td class="t-player2">Касымхан Байсеитов</td>
                </tr>
                <tr>
                    <td class="t-date">08.12.25</td>
                    <td class="t-player1">Алмасбек Утегенов</td>
                    <td class="t-result">3:2</td>
                    <td class="t-player2">Касымхан Байсеитов</td>
                </tr>
                <tr>
                    <td class="t-date">08.12.25</td>
                    <td class="t-player1">Алмасбек Утегенов</td>
                    <td class="t-result">3:2</td>
                    <td class="t-player2">Касымхан Байсеитов</td>
                </tr>
                <tr>
                    <td class="t-date">08.12.25</td>
                    <td class="t-player1">Алмасбек Утегенов</td>
                    <td class="t-result">3:2</td>
                    <td class="t-player2">Касымхан Байсеитов</td>
                </tr>
            </tbody>
        </table>
    </section>

    <script>
        // Wait until the DOM is fully loaded
        document.addEventListener('DOMContentLoaded', () => {
            const burger = document.querySelector('.burger');
            const menu = document.querySelector('.right');

            burger.addEventListener('click', () => {
                menu.classList.toggle('active'); // slide in/out
            });
        });
    </script>
</body>
</html>

app/website/templates/login_page.html
{% extends 'base.html' %}

{% block content %}
<div class="login">
    <div class="login-inside">
        <h3>Панель Админа</h3>
        <form method="POST" action="{% url 'login_page' %}">
            {% csrf_token %}
            <input type="text" class="form-control" name="username" placeholder="Пользователь" required>
            <input type="password" class="form-control" name="password" placeholder="Пороль" required>
            <button type="submit" class="cta-button">Войти</button>
        </form>
    </div>
</div>
{% endblock %}

app/website/templates/navbar.html
{% load static %}

<header>
    <a href="{% url 'home' %}">
        <div class="left">
            <img src="{% static 'logo.svg' %}">
            <h2>РЕЙТИНГ ЭЛО</h2>
        </div> 
    </a>
    <div class="right">
        <ul>
            <li><a href="{% url 'home' %}#player-section">Рейтинг</a></li>
            <li><a href="{% url 'home' %}#match-section">История матчей</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'control_center' %}">Настройки</a></li>
            {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <a href="{% url 'logout_user' %}" class="cta-button">Выйти</a>
        {% else %}
        <a href="{% url 'login_page' %}" class="cta-button">Войти</a>
        {% endif %}
    </div>
    <a class="burger" href="#">
        <span></span>
        <span></span>
        <span></span>
    </a>
</header>